### ISSUE TITLE
Catalog list items not clickable

### ISSUE THREAD

**Issue by bmartz** [WheresMyBus/android#13]
Since the addition of the favorite button, the actual list items in both the route and neighborhood views of the catalog are no longer clickable. The problem likely has to do with the favorite button obscuring the click on the list item somehow.

**Comment by beleslie** [comment]
Fixed in https://github.com/WheresMyBus/android/commit/c60021cd1b2a38e62e240ab27134f15cc875a149

**Comment by beleslie** [comment]
The solution: I added the attribute android:descendantFocusability="blocksDescendants" to the header of the layout files that specified the layout of each view in the list view.
