### ISSUE TITLE
App crashes when neighborhood is clicked from the catalog

### ISSUE THREAD

**Issue by bmartz** [WheresMyBus/android#14]
Selecting a neighborhood which has alerts from the catalog view crashes the app due to a null pointer exception. This is a problem in the NeighborhoodAlertAdapter.

Clicking Ballard crashes the app, but Admiral and Alki don't.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.widget.TextView.getText()' on a null object reference
                      at adapters.NeighborhoodAlertAdapter.getView(NeighborhoodAlertAdapter.java:71)

**Comment by dhouty** [comment]
Fixed in 5cc778c52f1f1f9d857a4f35cb018533c0e56569
