### ISSUE TITLE
Catalog page hides the last item in the list

### ISSUE THREAD

**Issue by dhouty** [WheresMyBus/android#15]
On our catalog page, the android navigation bar covers the last item in the list.

**Comment by bmartz** [comment]
One solution is to use a RecyclerView instead of a ListView to get the layout and scrolling to both work, but this breaks our adapaters. (ArrayAdapter is not compatible with RecyclerView.)

The solution I found was to add padding to the bottom of the ListView.

**Comment by bmartz** [comment]
Fixed https://github.com/WheresMyBus/android/commit/f53ad466b14207c29985923ec592d37d86238228
