### ISSUE TITLE
Clicking submit alert button on forum page crashes app

### ISSUE THREAD

**Issue by bmartz** [WheresMyBus/android#17]
The problem is in the NeighborhoodAdapter (presumably the same goes for route) when it tries the get the context, SubmitAlertActivity is returned when it expects CatalogActivity after clicking the submit alert button.

Ideally, clicking the button should take the user directly to the submit alert page and the adapter shouldn't be called and then throw an error. I'm not sure if the solution is to change the context to a general Activity, or to try not to enter adapter.getView method when the button is clicked (the second option seems harder).

java.lang.ClassCastException: com.wheresmybus.SubmitAlertActivity cannot be cast to com.wheresmybus.CatalogActivity
                      at adapters.NeighborhoodAdapter.getView(NeighborhoodAdapter.java:39)

**Comment by dhouty** [comment]
Fixed 9f2e864956e9d081b2a61b23271442e5f2ff0af8
