### ISSUE TITLE
Route alerts not showing up on forum page

### ISSUE THREAD

**Issue by dhouty** [WheresMyBus/android#18]

**Comment by bmartz** [comment]
I think this is the same as this issue I made earlier: https://github.com/WheresMyBus/android/issues/12

I should've been more specific in the title that it was just route alerts, but when we dug into the problem it looked like the response received from the database for route alerts was empty.

**Comment by dhouty** [comment]
Oops. I probably should have looked more carefully before I made this issue. It turns out that we were passing the route number to the server instead of the route id.
