### ISSUE TITLE
Alerts and comments just submitted are not displayed

### ISSUE THREAD

**Issue by beleslie** [WheresMyBus/android#20]
When I navigate to a forum and click the button to submit an alert, I submit an alert and the app returns me to the forum page. However, when this happens, the alert is not displayed in the forum. To view the alert, I have to navigate backward in the app and then return to the forum page. Similar behavior occurs when I submit a comment and the app returns me to the alert page for which I submitted a comment.

**Comment by bmartz** [comment]
Alerts fixed https://github.com/WheresMyBus/android/commit/013cd62ad9b299fd7a383da010a7ef6efcd37ec1

**Comment by bmartz** [comment]
Comments fixed https://github.com/WheresMyBus/android/commit/3264efa5207580bee1459bd593cc3d7cd412c141
