### ISSUE TITLE
Favorites just added/removed are not shown properly when switch is clicked

### ISSUE THREAD

**Issue by bmartz** [WheresMyBus/android#21]
If you add or remove a favorite route/neighborhood by clicking the favorite button (star icon) and then turn the view favorites only switch to on, the new favorites are not displayed - the favorites list from before the current session is shown.

**Comment by bmartz** [comment]
Adding fixed 78d8af0d90a5602a19a18bd9d8c27fb6f0686985

**Comment by nbissiri** [comment]
Several of us agree that this is working in a pretty good way now
