### ISSUE TITLE
The number of upvotes or downvotes an alert or comment has is not displayed accurately

### ISSUE THREAD

**Issue by beleslie** [WheresMyBus/android#24]
When I upvote or downvote an alert or comment, the page increments the number of upvotes or downvotes shown below the thumbs up or down button. However, the next time I view the alert or comment on the forum or specific alert page, the number of upvotes or downvotes displayed is not correct.

**Comment by nbissiri** [comment]
This should be fixed in the latest commit, the call to setText() was causing an error because it requires a String as an argument and was receiving and int
