### ISSUE TITLE
If the alert description is above a certain length, the numThumbsUp is not displayed in forum view

### ISSUE THREAD

**Issue by nbissiri** [WheresMyBus/android#36]

**Comment by nbissiri** [comment]
The same thing happens if the title of the alert is long.

**Comment by nbissiri** [comment]
UPDATE this only happens for neighborhood alerts, converting the layout file for these to match route alerts would probably fix it

**Comment by beleslie** [comment]
Fixed in https://github.com/WheresMyBus/android/commit/e993a9e001f34dd99a24adfa82c80bc435a45bfd
